### ISSUE TITLE
Question: Can nixcrpkgs be used to crosscompile nixpkgs package?

### ISSUE THREAD

**Issue by tex** [DavidEGrayson/nixcrpkgs#18]
This is a question, I want to cross compile some nixpkgs package on Linux to Windows.

**Comment by DavidEGrayson** [comment]
That is an interesting idea, but no, nixcrpkgs makes no attempt to support the format of nixpkgs package recipes.  I am not a fan of how complicated those recipes are, both on the Nix side and in the builder shell scripts.  I prefer simple, explicit steps instead having a bunch of stuff get generated for me automatically.
